### ISSUE TITLE
Service Account template is referring to .Release.Name whilst image-pull-secret is using .Release.Namespace

### ISSUE THREAD

**Issue by beachfires** [aquasecurity/aqua-helm#255]
https://github.com/aquasecurity/aqua-helm/blob/a8cc2531ea0ea9d9e23e24aa559ff2fb6902c281/server/templates/image-pull-secret.yaml#L6

I'm having trouble deploying aqua server using helm. After populating the values.yml file with the correct values for `imageCredentials`, my pods cannot pull the images from the private registries as they getting a 401 Unauthorized. After a bit of digging it seems like the service account cannot find the image-pull-secret created by helm due to the following:

The Service account template is using `{{ .Release.Name }}-registry-secret` when referring to the registry secret, however, the image-pull-secret template is using `{{ .Release.Namespace }}-registry-secret` as its name. Both are set when the `.Values.imageCredentials` boolean value is set to true, and causes the service account to not find the secret.

Perhaps I'm missing something here? Otherwise, it seems like a bug.

Looking forward to understanding the issue.

**Comment by KoppulaRajender** [comment]
It is a bug, fixed in #256.
The registry secret name should be with the name aqua (as namespace recommended).

**Comment by beachfires** [comment]
Hi, I've pulled the 6.0.1 Server helm chart, it is still showing this bug. I thought it was fixed in 6.0.1?
