### ISSUE TITLE
Cannot install server chart with Helm 3.2.1

### ISSUE THREAD

**Issue by cdunford** [aquasecurity/aqua-helm#83]
The server chart fails to install with `helm 3.2.1`:

Command:
```
helm install aqua-server aqua-helm/server -n aqua --create-namespace --set imageCredentials.username=test,imageCredentials.password=test
```

Result:
```
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/cdunford/.cache/helm/repository/server-4.6.0.tgz

Error: template: server/templates/web-secrets.yaml:2:11: executing "server/templates/web-secrets.yaml" at <(.Values.admin.password) .Values.admin.token>: can't give argument to non-function .Values.admin.password
helm.go:84: [debug] template: server/templates/web-secrets.yaml:2:11: executing "server/templates/web-secrets.yaml" at <(.Values.admin.password) .Values.admin.token>: can't give argument to non-function .Values.admin.password
```

The same command is successful with `helm 3.2.0`:

Result:
```
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/cdunford/.cache/helm/repository/server-4.6.0.tgz

client.go:108: [debug] creating 1 resource(s)
client.go:258: [debug] Starting delete for "aqua-server-database-password" Secret
client.go:108: [debug] creating 1 resource(s)
client.go:108: [debug] creating 13 resource(s)
NAME: aqua-server
LAST DEPLOYED: Fri May 15 12:30:56 2020
NAMESPACE: aqua
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
imageCredentials:
  password: test
  username: test

COMPUTED VALUES:
activeactive: true
admin:
  password: null
  passwordkey: null
  secretname: null
  token: null
  tokenkey: null
clustermode: false
db:
  affinity: {}
  dbPasswordKey: null
  dbPasswordName: null
  external:
    auditName: null
    enabled: false
    host: null
    name: null
    password: null
    port: null
    pubsubName: null
    user: null
  image:
    pullPolicy: IfNotPresent
    repository: database
    tag: "4.6"
  livenessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host $POD_IP
    failureThreshold: 6
    initialDelaySeconds: 60
    timeoutSeconds: 5
  nodeSelector: {}
  passwordSecret: null
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 30Gi
    storageClass: null
  readinessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host $POD_IP
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 0.1
      memory: 0.2Gi
  service:
    type: ClusterIP
  ssl: false
  tolerations: []
docker:
  socket:
    path: /var/run/docker.sock
dockerless: false
gate:
  affinity: {}
  grpcservice:
    externalPort: 8443
    nodePort: null
    type: ClusterIP
  image:
    pullPolicy: IfNotPresent
    repository: gateway
    tag: "4.6"
  livenessProbe: {}
  nodeSelector: {}
  publicIP: aqua-gateway
  readinessProbe: {}
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.1
      memory: 0.2Gi
  service:
    externalPort: 3622
    nodePort: null
    type: ClusterIP
  tolerations: []
imageCredentials:
  create: true
  name: csp-registry-secret
  password: test
  registry: registry.aquasec.com
  repositoryUriPrefix: registry.aquasec.com
  username: test
rbac:
  enabled: true
  privileged: true
  roleRef: null
scanner:
  affinity: {}
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: scanner
    tag: "4.6"
  livenessProbe: {}
  nodeSelector: {}
  password: null
  readinessProbe: {}
  replicaCount: 1
  resources: {}
  tolerations: []
  user: null
web:
  affinity: {}
  encryptionKey: null
  image:
    pullPolicy: IfNotPresent
    repository: console
    tag: "4.6"
  ingress:
    annotations: {}
    enabled: false
    hosts: null
    tls: []
  livenessProbe: {}
  nodeSelector: {}
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 4
    storageClass: null
  proxy:
    httpProxy: null
    httpsProxy: null
    noProxy: null
  readinessProbe: {}
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.1
      memory: 0.2Gi
  service:
    externalPort: 8080
    nodePort: null
    type: ClusterIP
  tolerations: []

HOOKS:
---
# Source: server/templates/db-password-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aqua-server-database-password
  labels:
    app: aqua-server-database
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  db-password: "T1ByV21CTHhlWm5RMDhEVkdCcUQ="
MANIFEST:
---
# Source: server/templates/rbac.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
    name: aqua-server-psp
    labels:
      app: aqua-server
      chart: "server-4.6.0"
      release: "aqua-server"
      heritage: "Helm"
spec:
  privileged: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
# Source: server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aqua-server-sa
  labels:
    app: aqua-server
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
imagePullSecrets:
- name: aqua-server-registry-secret
---
# Source: server/templates/image-pull-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aqua-server-registry-secret
  labels:
    app: aqua-server
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsicmVnaXN0cnkuYXF1YXNlYy5jb20iOiB7ImF1dGgiOiAiZEdWemREcDBaWE4wIn19fQ==
---
# Source: server/templates/db-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aqua-server-database-pvc
  labels:
    app: aqua-server
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "30Gi"
---
# Source: server/templates/web-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aqua-server-web-pvc
  labels:
    app: aqua-server
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "4Gi"
---
# Source: server/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aqua-server-cluster-role
  labels:
    app: aqua-server
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
    rbac.example.com/aggregate-to-monitoring: "true"
rules:
- apiGroups: ["extensions"]
  resourceNames: [aqua-server-psp]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
- apiGroups: [""]
  resources: ["nodes", "services", "endpoints", "pods", "deployments", "namespaces","componentstatuses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
# Source: server/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aqua-server-role-binding
  namespace: aqua
  labels:
    app: aqua-server
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
subjects:
  - kind: ServiceAccount
    name: aqua-server-sa
    namespace: aqua
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: aqua-server-cluster-role
---
# Source: server/templates/db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aqua-server-database-svc
  labels:
    app: aqua-server-database
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
spec:
  type: ClusterIP
  selector:
    app: aqua-server-database
  ports:
    - port: 5432
---
# Source: server/templates/gate-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aqua-server-gateway-svc
  labels:
    app: aqua-server-gateway
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
spec:
  type: ClusterIP
  selector:
    app: aqua-server-gateway
  ports:
  - port: 3622
    targetPort: 3622
    protocol: TCP
    name: aqua-gate
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: aqua-gate-ssl
---
# Source: server/templates/web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aqua-server-console-svc
  labels:
    app: aqua-server-console
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
spec:
  type: ClusterIP
  selector:
    app: aqua-server-console
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: aqua-server-console
  - port: 443
    protocol: TCP
    targetPort: 8443
    name: aqua-web-ssl
---
# Source: server/templates/db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-server-database
  labels:
    app: aqua-server-database
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app: aqua-server-database
  template:
    metadata:
      annotations:
      labels:
        app: aqua-server-database
      name: aqua-server-database
    spec:
      serviceAccount: aqua-server-sa
      containers:
      - name: db
        image: "registry.aquasec.com/database:4.6"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aqua-server-database-password
              key: db-password
        - name: PGDATA
          value: "/var/lib/postgresql/data/db-files"
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-database
        ports:
        - containerPort: 5432
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          failureThreshold: 6
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.1
            memory: 0.2Gi
      volumes:
      - name: postgres-database
        persistentVolumeClaim:
          claimName: aqua-server-database-pvc
---
# Source: server/templates/gate-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-server-gateway
  labels:
    app: aqua-server-gateway
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-server-gateway
  template:
    metadata:
      annotations:
      labels:
        app: aqua-server-gateway
      name: aqua-server-gateway
    spec:
      serviceAccount: aqua-server-sa
      containers:
      - name: gate
        image: "registry.aquasec.com/gateway:4.6"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: AQUA_CONSOLE_SECURE_ADDRESS
          value: "aqua-server-console-svc:443"
        - name: SCALOCK_GATEWAY_PUBLIC_IP
          value: aqua-gateway
        - name: HEALTH_MONITOR
          value: "0.0.0.0:8082"
        - name: SCALOCK_DBUSER
          value: postgres
        - name: SCALOCK_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: aqua-server-database-password
              key: db-password
        - name: SCALOCK_DBNAME
          value: scalock
        - name: SCALOCK_DBHOST
          value: aqua-server-database-svc
        - name: SCALOCK_DBPORT
          value: "5432"
        - name: SCALOCK_AUDIT_DBUSER
          value: postgres
        - name: SCALOCK_AUDIT_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: aqua-server-database-password
              key: db-password
        - name: SCALOCK_AUDIT_DBNAME
          value: slk_audit
        - name: SCALOCK_AUDIT_DBHOST
          value: aqua-server-database-svc
        - name: SCALOCK_AUDIT_DBPORT
          value: "5432"
        - name: AQUA_PUBSUB_DBUSER
          value: postgres
        - name: AQUA_PUBSUB_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: aqua-server-database-password
              key: db-password
        - name: AQUA_PUBSUB_DBNAME
          value: aqua_pubsub
        - name: AQUA_PUBSUB_DBHOST
          value: aqua-server-database-svc
        - name: AQUA_PUBSUB_DBPORT
          value: "5432"
        ports:
        - containerPort: 3622
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.1
              memory: 0.2Gi
---
# Source: server/templates/web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-server-console
  labels:
    app: aqua-server-console
    chart: "server-4.6.0"
    release: "aqua-server"
    heritage: "Helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-server-console
  template:
    metadata:
      annotations:
      labels:
        app: aqua-server-console
      name: aqua-server-console
    spec:
      serviceAccount: aqua-server-sa
      containers:
      - name: web
        image: "registry.aquasec.com/console:4.6"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: SCALOCK_DBUSER
          value: postgres
        - name: SCALOCK_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: aqua-server-database-password
              key: db-password
        - name: SCALOCK_DBNAME
          value: scalock
        - name: SCALOCK_DBHOST
          value: aqua-server-database-svc
        - name: SCALOCK_DBPORT
          value: "5432"
        - name: SCALOCK_AUDIT_DBUSER
          value: postgres
        - name: SCALOCK_AUDIT_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: aqua-server-database-password
              key: db-password
        - name: SCALOCK_AUDIT_DBNAME
          value: slk_audit
        - name: SCALOCK_AUDIT_DBHOST
          value: aqua-server-database-svc
        - name: SCALOCK_AUDIT_DBPORT
          value: "5432"
        - name: AQUA_PUBSUB_DBUSER
          value: postgres
        - name: AQUA_PUBSUB_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: aqua-server-database-password
              key: db-password
        - name: AQUA_PUBSUB_DBNAME
          value: aqua_pubsub
        - name: AQUA_PUBSUB_DBHOST
          value: aqua-server-database-svc
        - name: AQUA_PUBSUB_DBPORT
          value: "5432"
        - name: AQUA_DOCKERLESS_SCANNING
          value: "0"
        - name: AQUA_PPROF_ENABLED
          value: "0"
        - name: DISABLE_IP_BAN
          value: "0"
        - name: AQUA_CLUSTER_MODE
          value: "active-active"
        - name: AQUA_CONSOLE_RAW_SCAN_RESULTS_STORAGE_SIZE
          value: "4"
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket-mount
        - mountPath: /opt/aquasec/raw-scan-results
          name: aqua-web-pvc
        resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.1
              memory: 0.2Gi
      volumes:
      - name: docker-socket-mount
        hostPath:
          path: /var/run/docker.sock
      - name: aqua-web-pvc
        persistentVolumeClaim:
          claimName: aqua-server-web-pvc

NOTES:
Thank you for installing Aqua Security Server.

Now that you have deployed Aqua Server, you should look over the docs on using: 

https://read.aquasec.com/docs


Your release is named aqua-server. To learn more about the release, try:

  $ helm status aqua-server
  $ helm get aqua-server
```

**Comment by niso120b** [comment]
Tested and its works please use default values.yaml file

**Comment by cdunford** [comment]
@niso120b 

I just retested this yesterday with the 4.6 chart published on https://helm.aquasec.com and helm 3.2.4 and it is still an issue. I am not sure what you mean by use the default values.yaml - of course I need to specify my own configuration. I think the problematic value here is `.Values.admin.password`. We are specifying this value, whereas using the defaults would not.

Can you please reopen this.

**Comment by niso120b** [comment]
You used your own values.yaml?

**Comment by cdunford** [comment]
I don't use my own values.yaml per se, but I override default values for my use case of course.

Is what's on helm.aquasec.com not what is in github?

**Comment by cdunford** [comment]
@niso120b have you been able to replicate?

**Comment by niso120b** [comment]
Can you try now

**Comment by cdunford** [comment]
Still an issue on the 4.6 branch:

```
❯ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.14.4"}

~/src/aqua-helm/server | @d5bdf9dd
❯ helm template test .
Error: template: server/templates/web-secrets.yaml:2:11: executing "server/templates/web-secrets.yaml" at <(.Values.admin.password) .Values.admin.token>: can't give argument to non-function .Values.admin.password
```

Also still an issue on the 5.0 branch:

```
❯ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.14.4"}

~/src/aqua-helm/server | @d40a42a8 
❯ helm template test .
Error: template: server/templates/web-secrets.yaml:2:11: executing "server/templates/web-secrets.yaml" at <(.Values.admin.password) .Values.admin.token>: can't give argument to non-function .Values.admin.password
```

Appears to be resolved by #101 

```
❯ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.14.4"}

~/src/aqua-helm/server | @d9212f56 
❯ helm template test . --set 'imageCredentials.username=test,imageCredentials.password=test'
---
# Source: server/templates/rbac.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
....
```

**Comment by cdunford** [comment]
@niso120b - this is resolved by #101 on master. I don't quite understand the branching strategy in this repo. Is the `5.0` branch the release branch for 5.0? Can this fix be ported to that branch?

**Comment by devopskid** [comment]
This is still an issue for me as well. I am running helm version 3.2.4 and pulling from the master branch, trying to deploy aqua-server from helm chart version 5.0.0. The deployment of my helmRelease fails due to the same issue:

`Warning  FailedReleaseSync  14s (x3 over 3m46s)  helm-operator  synchronization of release 'aqua-server' in namespace 'aqua' failed: installation failed: template: server/templates/web-secrets.yaml:2:11: executing "server/templates/web-secrets.yaml" at <(.Values.admin.password) .Values.admin.token>: can't give argument to non-function .Values.admin.password`

**Comment by KoppulaRajender** [comment]
@devopskid - can you check again with latest 5.0 version. It is working for me with helm 3.2.4 version + 5.0 helm charts.
